name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Adjust according to your project's Java version
          distribution: ''

      # Install dependencies and build the project
      - name: Build project
        run: |
          ./gradlew build # If you use Gradle
          # mvn clean install # Uncomment if you use Maven

      # Run tests
      - name: Run tests
        run: ./gradlew test # Replace with Maven equivalent if needed
